import type { Translations } from '../../type/translations';

/**
 * Fully resolved message ready to be rendered.
 *
 * Returned by the factory functions generated by `defineMessageCatalog`.
 * Pass it to {@link resolveMessage} to get the final string for a given locale.
 */
export interface ResolvedMessage {
	/** All available translations keyed by locale. */
	readonly translations: Translations;

	/** Parameter values to interpolate into `{{placeholder}}` tokens. */
	readonly params?: Readonly<Record<string, string>> | undefined;

	/** Locale used when no explicit locale is passed to `resolveMessage`. */
	readonly defaultLocale: string;
}
